FROM node:lts

ENV DEBCONF_NOWARNINGS yes

#RUN apt-get update
#RUN apt-get install -y curl
#RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
#RUN tee /etc/apt/sources.list.d/yarn.list
#RUN apt-get install -y yarn
#RUN yarn global add @angular/cli

ENV TZ Asia/Tokyo
#ENV PATH $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH

EXPOSE 4200

WORKDIR /app

CMD ["/bin/bash"]