version: '3.4'
services:
  mbo_front:
    container_name: mbofrontapp
    build:
      context: ./
      dockerfile: dockerfile.front
    ports:
      - 4200:4200
    volumes:
      - ../app/angular-app:/app
    stdin_open: true
    tty: true
    restart: always
  mbo_appserver:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: mboserverapp
    restart: always
    ports:
      - "18080:80"
    environment:
      TZ: "Asia/Tokyo"
      ASPNETCORE_CONTENTROOT: "/app"
      ASPNETCORE_ENVIRONMENT: "Development" # "Production" or "Development"
#      Database__db: "server=myappdb;port=3306;database=myapp;user id=myapp;password=insecure;sslmode=none;"
    volumes:
      - "./app/dotnet-app:/app"
    entrypoint: ["dotnet", "/app/server.dll"]